name: Build Debian Releases

on:
  - push
  - workflow_dispatch

jobs:
  build-debian:
    strategy:
      matrix:
        debian: [bookworm, trixie]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: debian:${{ matrix.debian }}
      options: --cap-add NET_ADMIN
    steps:
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y \
            curl \
            build-essential \
            pkg-config \
            libnftnl-dev \
            libmnl-dev \
            nftables \
            python3-numpy \
            git
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Bench
        run: cargo bench
      - name: Build release binaries
        run: cargo build --release
      - name: Verify binaries
        run: |
          ldd target/release/leroyjenkins
          ./target/release/leroyjenkins --version
      - name: Integration test
        run: |
          nft add table inet leroy
          nft add set inet leroy leroy4 '{ type ipv4_addr; size 2000; flags timeout; }'
          nft add set inet leroy leroy6 '{ type ipv6_addr; size 2000; flags timeout; }'
          python3 zipf-ips.py --seed=42 -4 | head -n 200000 | RUST_LOG=info ./target/release/leroyjenkins --bl-threshold=0 --ban-base-time=120s --ban-ttl=1d
          nft list set inet leroy leroy4 | grep -qP '\d+\.\d+\.\d+\.\d+'
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: leroyjenkins-debian-${{ matrix.debian }}
          path: |
            target/release/leroyjenkins
          retention-days: 90
  release:
    needs: build-debian
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Bookworm artifact
        uses: actions/download-artifact@v7
        with:
          name: leroyjenkins-debian-bookworm
          path: bookworm
      - name: Download Trixie artifact
        uses: actions/download-artifact@v7
        with:
          name: leroyjenkins-debian-trixie
          path: trixie
      - name: Organize release files
        run: |
          mv bookworm/leroyjenkins leroyjenkins-debian-bookworm
          mv trixie/leroyjenkins leroyjenkins-debian-trixie
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            leroyjenkins-debian-*
          fail_on_unmatched_files: true
